version: '3.8'

# Configuración para desarrollo con hot-reload

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./db/database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/poblar_base_datos_completa.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
  # Solo MySQL para desarrollo, backend y frontend se ejecutan localmente

volumes:
  mysql_data_dev:
    driver: local

networks:
  ecommerce-network:
    driver: bridge
