/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteRouteImport } from './routes/productos/route'
import { Route as GestionarRouteRouteImport } from './routes/gestionar/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ProductosIndexRouteImport } from './routes/productos/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GestionarIndexRouteImport } from './routes/gestionar/index'
import { Route as ForgotIndexRouteImport } from './routes/forgot/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as ProductosIdRouteImport } from './routes/productos/$id'
import { Route as GestionarAgregarRouteImport } from './routes/gestionar/agregar'
import { Route as ProductosCategoriasNombreRouteImport } from './routes/productos/categorias/$nombre'
import { Route as GestionarEditarProductIdRouteImport } from './routes/gestionar/editar/$productId'

const ProductosRouteRoute = ProductosRouteRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionarRouteRoute = GestionarRouteRouteImport.update({
  id: '/gestionar',
  path: '/gestionar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductosRouteRoute,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionarIndexRoute = GestionarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestionarRouteRoute,
} as any)
const ForgotIndexRoute = ForgotIndexRouteImport.update({
  id: '/forgot/',
  path: '/forgot/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIdRoute = ProductosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductosRouteRoute,
} as any)
const GestionarAgregarRoute = GestionarAgregarRouteImport.update({
  id: '/agregar',
  path: '/agregar',
  getParentRoute: () => GestionarRouteRoute,
} as any)
const ProductosCategoriasNombreRoute =
  ProductosCategoriasNombreRouteImport.update({
    id: '/categorias/$nombre',
    path: '/categorias/$nombre',
    getParentRoute: () => ProductosRouteRoute,
  } as any)
const GestionarEditarProductIdRoute =
  GestionarEditarProductIdRouteImport.update({
    id: '/editar/$productId',
    path: '/editar/$productId',
    getParentRoute: () => GestionarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestionar': typeof GestionarRouteRouteWithChildren
  '/productos': typeof ProductosRouteRouteWithChildren
  '/gestionar/agregar': typeof GestionarAgregarRoute
  '/productos/$id': typeof ProductosIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/forgot': typeof ForgotIndexRoute
  '/gestionar/': typeof GestionarIndexRoute
  '/login': typeof LoginIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/signup': typeof SignupIndexRoute
  '/gestionar/editar/$productId': typeof GestionarEditarProductIdRoute
  '/productos/categorias/$nombre': typeof ProductosCategoriasNombreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestionar/agregar': typeof GestionarAgregarRoute
  '/productos/$id': typeof ProductosIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/forgot': typeof ForgotIndexRoute
  '/gestionar': typeof GestionarIndexRoute
  '/login': typeof LoginIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/productos': typeof ProductosIndexRoute
  '/signup': typeof SignupIndexRoute
  '/gestionar/editar/$productId': typeof GestionarEditarProductIdRoute
  '/productos/categorias/$nombre': typeof ProductosCategoriasNombreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestionar': typeof GestionarRouteRouteWithChildren
  '/productos': typeof ProductosRouteRouteWithChildren
  '/gestionar/agregar': typeof GestionarAgregarRoute
  '/productos/$id': typeof ProductosIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/forgot/': typeof ForgotIndexRoute
  '/gestionar/': typeof GestionarIndexRoute
  '/login/': typeof LoginIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/gestionar/editar/$productId': typeof GestionarEditarProductIdRoute
  '/productos/categorias/$nombre': typeof ProductosCategoriasNombreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gestionar'
    | '/productos'
    | '/gestionar/agregar'
    | '/productos/$id'
    | '/checkout'
    | '/forgot'
    | '/gestionar/'
    | '/login'
    | '/perfil'
    | '/productos/'
    | '/signup'
    | '/gestionar/editar/$productId'
    | '/productos/categorias/$nombre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gestionar/agregar'
    | '/productos/$id'
    | '/checkout'
    | '/forgot'
    | '/gestionar'
    | '/login'
    | '/perfil'
    | '/productos'
    | '/signup'
    | '/gestionar/editar/$productId'
    | '/productos/categorias/$nombre'
  id:
    | '__root__'
    | '/'
    | '/gestionar'
    | '/productos'
    | '/gestionar/agregar'
    | '/productos/$id'
    | '/checkout/'
    | '/forgot/'
    | '/gestionar/'
    | '/login/'
    | '/perfil/'
    | '/productos/'
    | '/signup/'
    | '/gestionar/editar/$productId'
    | '/productos/categorias/$nombre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestionarRouteRoute: typeof GestionarRouteRouteWithChildren
  ProductosRouteRoute: typeof ProductosRouteRouteWithChildren
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ForgotIndexRoute: typeof ForgotIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestionar': {
      id: '/gestionar'
      path: '/gestionar'
      fullPath: '/gestionar'
      preLoaderRoute: typeof GestionarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof ProductosRouteRoute
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestionar/': {
      id: '/gestionar/'
      path: '/'
      fullPath: '/gestionar/'
      preLoaderRoute: typeof GestionarIndexRouteImport
      parentRoute: typeof GestionarRouteRoute
    }
    '/forgot/': {
      id: '/forgot/'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$id': {
      id: '/productos/$id'
      path: '/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof ProductosIdRouteImport
      parentRoute: typeof ProductosRouteRoute
    }
    '/gestionar/agregar': {
      id: '/gestionar/agregar'
      path: '/agregar'
      fullPath: '/gestionar/agregar'
      preLoaderRoute: typeof GestionarAgregarRouteImport
      parentRoute: typeof GestionarRouteRoute
    }
    '/productos/categorias/$nombre': {
      id: '/productos/categorias/$nombre'
      path: '/categorias/$nombre'
      fullPath: '/productos/categorias/$nombre'
      preLoaderRoute: typeof ProductosCategoriasNombreRouteImport
      parentRoute: typeof ProductosRouteRoute
    }
    '/gestionar/editar/$productId': {
      id: '/gestionar/editar/$productId'
      path: '/editar/$productId'
      fullPath: '/gestionar/editar/$productId'
      preLoaderRoute: typeof GestionarEditarProductIdRouteImport
      parentRoute: typeof GestionarRouteRoute
    }
  }
}

interface GestionarRouteRouteChildren {
  GestionarAgregarRoute: typeof GestionarAgregarRoute
  GestionarIndexRoute: typeof GestionarIndexRoute
  GestionarEditarProductIdRoute: typeof GestionarEditarProductIdRoute
}

const GestionarRouteRouteChildren: GestionarRouteRouteChildren = {
  GestionarAgregarRoute: GestionarAgregarRoute,
  GestionarIndexRoute: GestionarIndexRoute,
  GestionarEditarProductIdRoute: GestionarEditarProductIdRoute,
}

const GestionarRouteRouteWithChildren = GestionarRouteRoute._addFileChildren(
  GestionarRouteRouteChildren,
)

interface ProductosRouteRouteChildren {
  ProductosIdRoute: typeof ProductosIdRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
  ProductosCategoriasNombreRoute: typeof ProductosCategoriasNombreRoute
}

const ProductosRouteRouteChildren: ProductosRouteRouteChildren = {
  ProductosIdRoute: ProductosIdRoute,
  ProductosIndexRoute: ProductosIndexRoute,
  ProductosCategoriasNombreRoute: ProductosCategoriasNombreRoute,
}

const ProductosRouteRouteWithChildren = ProductosRouteRoute._addFileChildren(
  ProductosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestionarRouteRoute: GestionarRouteRouteWithChildren,
  ProductosRouteRoute: ProductosRouteRouteWithChildren,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ForgotIndexRoute: ForgotIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
